In [1]:
import numpy as np

In [2]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
u = np.empty(8)
u

array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323,
 3.0e-323, 3.5e-323])

In [6]:
d = np.arange(1,99,3)
d

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [8]:
h = [5,4,12,5,90,35,73,24,67,43,2]
print(h)
print(type(h))

print(type(d))

[5, 4, 12, 5, 90, 35, 73, 24, 67, 43, 2]
<class 'list'>
<class 'numpy.ndarray'>


In [9]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [11]:
mlista = np.array([56,3,1,2,6,7,89,35,3])
mlista

array([56, 3, 1, 2, 6, 7, 89, 35, 3])

In [12]:
print(type(mlista))

<class 'numpy.ndarray'>


In [13]:
gglista = np.array(h)
gglista

array([ 5, 4, 12, 5, 90, 35, 73, 24, 67, 43, 2])

In [14]:
kl = (23,67,88,9,1,4,5,13)
print(kl)
print(type(kl))

(23, 67, 88, 9, 1, 4, 5, 13)
<class 'tuple'>


In [15]:
npk = np.array(kl)
print(npk)
print(type(npk))

[23 67 88  9  1  4  5 13]
<class 'numpy.ndarray'>
