In [1]:
import numpy as np

In [2]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
u = np.empty(8)
u

array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323,
 3.0e-323, 3.5e-323])

In [6]:
d = np.arange(1,99,3)
d

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [8]:
h = [5,4,12,5,90,35,73,24,67,43,2]
print(h)
print(type(h))

print(type(d))

[5, 4, 12, 5, 90, 35, 73, 24, 67, 43, 2]
<class 'list'>
<class 'numpy.ndarray'>


In [9]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [11]:
mlista = np.array([56,3,1,2,6,7,89,35,3])
mlista

array([56, 3, 1, 2, 6, 7, 89, 35, 3])

In [12]:
print(type(mlista))

<class 'numpy.ndarray'>


In [13]:
gglista = np.array(h)
gglista

array([ 5, 4, 12, 5, 90, 35, 73, 24, 67, 43, 2])

In [14]:
kl = (23,67,88,9,1,4,5,13)
print(kl)
print(type(kl))

(23, 67, 88, 9, 1, 4, 5, 13)
<class 'tuple'>


In [15]:
npk = np.array(kl)
print(npk)
print(type(npk))

[23 67 88  9  1  4  5 13]
<class 'numpy.ndarray'>


In [16]:
nb = [-7,0,1055,23,456,-678,1,4,88,990,199,-87,-234,657,222]
nbb = np.array(nb)

In [17]:
print(nbb)

[  -7    0 1055   23  456 -678    1    4   88  990  199  -87 -234  657
  222]


In [21]:
nb.sort()
print(nb)

[-678, -234, -87, -7, 0, 1, 4, 23, 88, 199, 222, 456, 657, 990, 1055]


In [22]:
nbb.sort()
print(nbb)

[-678 -234  -87   -7    0    1    4   23   88  199  222  456  657  990
 1055]


In [23]:
a = [4,6,8,3,63]
b = [54,2,67,1]
c = a+b
print(c)

[4, 6, 8, 3, 63, 54, 2, 67, 1]


In [24]:
an = np.array([3,8,16,4])
bn = np.array([18,23,333,2])

In [25]:
cn = an+bn
print(cn)

[ 21  31 349   6]


In [26]:
dn = np.concatenate((an,bn))
print(dn)

[  3   8  16   4  18  23 333   2]


In [27]:
#tworzenie macierzy
x = np.array([[12,7],[5,89]])
print(x)

[[12  7]
 [ 5 89]]


In [28]:
y = np.array([[111,57],[121,44]])
print(y)

[[111  57]
 [121  44]]


In [29]:
z = [[5,2],[17,2]]
print(z)

[[5, 2], [17, 2]]


In [31]:
print(y[1][0])

121


In [32]:
print(y[1,0])

121


In [33]:
print(z[0][0])

5


In [35]:
# print(z[0,0])

In [39]:
p = np.concatenate((x,y),axis=0)
print(p)

[[ 12   7]
 [  5  89]
 [111  57]
 [121  44]]


In [40]:
prosta = np.arange(12)
print(prosta)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [47]:
pp = prosta.reshape(3,4)
print(pp)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
pq = prosta.reshape(12)
print(pq)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [49]:
ar = np.array([1,6,78,9,112,7,88,345,89,900,12,34,57,23,5])
print(ar)

[  1   6  78   9 112   7  88 345  89 900  12  34  57  23   5]


In [50]:
print(ar.shape)

(15,)


In [51]:
print(ar[:4])

[ 1  6 78  9]


In [52]:
print(ar[5:])

[  7  88 345  89 900  12  34  57  23   5]


In [53]:
print(ar[2:7])

[ 78   9 112   7  88]


In [54]:
w = np.array([[1,2,3,4],[99,34,56,77],[21,13,14,35]])
print(w)

[[ 1  2  3  4]
 [99 34 56 77]
 [21 13 14 35]]


In [55]:
#filtorwanie macierzy
print(w[w<5])

[1 2 3 4]


In [56]:
pc = (w>=5)
print(w[pc])

[99 34 56 77 21 13 14 35]


In [57]:
parz = (w%2==0)
print(w[parz])

[ 2  4 34 56 14]


In [58]:
c = w[(w>2)&(w<21)]
print(c)

[ 3  4 13 14]


In [59]:
f = w[(w<8)|(w>50)]
print(f)

[ 1  2  3  4 99 56 77]
