In [1]:
import numpy as np

In [2]:
arr = np.array([[1.,2.,3.],[6.,7.,8.]])
arr

array([[1., 2., 3.],
 [6., 7., 8.]])

In [3]:
arr**2

array([[ 1., 4., 9.],
 [36., 49., 64.]])

In [4]:
arr-arr

array([[0., 0., 0.],
 [0., 0., 0.]])

In [5]:
1/arr

array([[1. , 0.5 , 0.33333333],
 [0.16666667, 0.14285714, 0.125 ]])

In [6]:
arr**0.5

array([[1. , 1.41421356, 1.73205081],
 [2.44948974, 2.64575131, 2.82842712]])

In [7]:
arr2 = np.array([[0.,4.,1.],[7.,5.,14.]])
arr2

array([[ 0., 4., 1.],
 [ 7., 5., 14.]])

In [8]:
arr2>arr

array([[False, True, False],
 [ True, False, True]])

In [9]:
#definicja tensora
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
arr3d[1]

array([[ 7, 8, 9],
 [10, 11, 12]])

In [11]:
old_values = arr3d[0].copy()
arr3d[0] = 45
arr3d

array([[[45, 45, 45],
        [45, 45, 45]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
arr3d[1,0,1]

8

In [14]:
arr3d.shape

(2, 2, 3)