In [1]:
import tensorflow as tf
print(f"wersja tensorflow: {tf.__version__}")

wersja tensorflow: 2.11.1


In [2]:
#ładowanie zbioru danych
mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [3]:
#model sieci neuronowej
model = tf.keras.models.Sequential(
    [
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
    ]
)

In [5]:
predictions = model(x_train[:1]).numpy()
print(predictions)

[[ 0.66880685 -0.03171099  0.31321555  0.58506376  0.21593782  0.08899727
  -0.37922585 -0.5973627   0.34501535 -0.25012967]]


In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.16481411, 0.0818019 , 0.11549497, 0.15157418, 0.10478904,
 0.09229673, 0.05778825, 0.04646265, 0.11922671, 0.06575146]],
 dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1],predictions).numpy()

2.3827467

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2953 - accuracy: 0.9150
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1428 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1083 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0893 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0760 - accuracy: 0.9760


In [11]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0744 - accuracy: 0.9774 - 586ms/epoch - 2ms/step


[0.07442735135555267, 0.977400004863739]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.32072929e-08, 7.51106342e-08, 1.69364539e-05, 9.50267859e-05,
        1.20685024e-11, 7.84832309e-07, 1.69797092e-13, 9.99886274e-01,
        3.41665356e-07, 6.56545410e-07],
       [1.04212838e-09, 2.16040116e-05, 9.99977469e-01, 9.16721945e-07,
        6.09960538e-15, 6.52554775e-08, 1.96262534e-10, 2.45287083e-15,
        3.04119889e-11, 3.31390603e-16],
       [1.01798392e-07, 9.98690188e-01, 1.18299620e-04, 2.01580460e-05,
        4.33330097e-05, 5.75256445e-06, 2.61421974e-06, 9.99730662e-04,
        1.04270192e-04, 1.56340502e-05],
       [9.99934435e-01, 1.50525050e-08, 3.51188428e-05, 6.57196892e-08,
        2.79081540e-08, 4.42351529e-06, 3.26422264e-06, 5.50011646e-06,
        2.60465729e-08, 1.71012489e-05],
       [3.08956260e-06, 1.36953187e-08, 8.38758388e-06, 3.80296008e-08,
        9.98007715e-01, 3.84618170e-06, 1.82636029e-06, 1.00147903e-04,
        1.82361305e-07, 1.87470915e-03]], dtype=float32)>